<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Foto_tabel extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Foto_tabel_model');
    } 

    /*
     * Listing of foto_tabel
     */
    function index()
    {
        $data['foto_tabel'] = $this->Foto_tabel_model->get_all_foto_tabel();
        
        $data['_view'] = 'foto_tabel/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new foto_tabel
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('PropertiID','PropertiID','required|max_length[50]');
		$this->form_validation->set_rules('Foto','Foto','required|max_length[100]');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'PropertiID' => $this->input->post('PropertiID'),
				'Foto' => $this->input->post('Foto'),
            );
            
            $foto_tabel_id = $this->Foto_tabel_model->add_foto_tabel($params);
            redirect('foto_tabel/index');
        }
        else
        {            
            $data['_view'] = 'foto_tabel/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a foto_tabel
     */
    function edit($FotoID)
    {   
        // check if the foto_tabel exists before trying to edit it
        $data['foto_tabel'] = $this->Foto_tabel_model->get_foto_tabel($FotoID);
        
        if(isset($data['foto_tabel']['FotoID']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('PropertiID','PropertiID','required|max_length[50]');
			$this->form_validation->set_rules('Foto','Foto','required|max_length[100]');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'PropertiID' => $this->input->post('PropertiID'),
					'Foto' => $this->input->post('Foto'),
                );

                $this->Foto_tabel_model->update_foto_tabel($FotoID,$params);            
                redirect('foto_tabel/index');
            }
            else
            {
                $data['_view'] = 'foto_tabel/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The foto_tabel you are trying to edit does not exist.');
    } 

    /*
     * Deleting foto_tabel
     */
    function remove($FotoID)
    {
        $foto_tabel = $this->Foto_tabel_model->get_foto_tabel($FotoID);

        // check if the foto_tabel exists before trying to delete it
        if(isset($foto_tabel['FotoID']))
        {
            $this->Foto_tabel_model->delete_foto_tabel($FotoID);
            redirect('foto_tabel/index');
        }
        else
            show_error('The foto_tabel you are trying to delete does not exist.');
    }
    
}
