<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Jenisproperti extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Jenisproperti_model');
    } 

    /*
     * Listing of jenisproperti
     */
    function index()
    {
        $data['jenisproperti'] = $this->Jenisproperti_model->get_all_jenisproperti();
        
        $data['_view'] = 'jenisproperti/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new jenisproperti
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('NamaJenis','NamaJenis','required|max_length[70]');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'NamaJenis' => $this->input->post('NamaJenis'),
            );
            
            $jenisproperti_id = $this->Jenisproperti_model->add_jenisproperti($params);
            redirect('jenisproperti/index');
        }
        else
        {            
            $data['_view'] = 'jenisproperti/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a jenisproperti
     */
    function edit($JenisID)
    {   
        // check if the jenisproperti exists before trying to edit it
        $data['jenisproperti'] = $this->Jenisproperti_model->get_jenisproperti($JenisID);
        
        if(isset($data['jenisproperti']['JenisID']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('NamaJenis','NamaJenis','required|max_length[70]');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'NamaJenis' => $this->input->post('NamaJenis'),
                );

                $this->Jenisproperti_model->update_jenisproperti($JenisID,$params);            
                redirect('jenisproperti/index');
            }
            else
            {
                $data['_view'] = 'jenisproperti/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The jenisproperti you are trying to edit does not exist.');
    } 

    /*
     * Deleting jenisproperti
     */
    function remove($JenisID)
    {
        $jenisproperti = $this->Jenisproperti_model->get_jenisproperti($JenisID);

        // check if the jenisproperti exists before trying to delete it
        if(isset($jenisproperti['JenisID']))
        {
            $this->Jenisproperti_model->delete_jenisproperti($JenisID);
            redirect('jenisproperti/index');
        }
        else
            show_error('The jenisproperti you are trying to delete does not exist.');
    }
    
}
