<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Properti extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Properti_model');
    } 

    /*
     * Listing of properti
     */
    function index()
    {
        $data['properti'] = $this->Properti_model->get_all_properti();
        
        $data['_view'] = 'properti/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new properti
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('JenisID','JenisID','required|max_length[50]');
		$this->form_validation->set_rules('NamaProperti','NamaProperti','required|max_length[50]');
		$this->form_validation->set_rules('Alamat_properti','Alamat Properti','required|max_length[200]');
		$this->form_validation->set_rules('Longitude','Longitude','required|max_length[50]');
		$this->form_validation->set_rules('Latitude','Latitude','required|max_length[50]');
		$this->form_validation->set_rules('Harga','Harga','required|integer');
		$this->form_validation->set_rules('Jarak','Jarak','required');
		$this->form_validation->set_rules('Jumlah_cicil','Jumlah Cicil','required|integer');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'JenisID' => $this->input->post('JenisID'),
				'NamaProperti' => $this->input->post('NamaProperti'),
				'Alamat_properti' => $this->input->post('Alamat_properti'),
				'Longitude' => $this->input->post('Longitude'),
				'Latitude' => $this->input->post('Latitude'),
				'Harga' => $this->input->post('Harga'),
				'Luas' => $this->input->post('Luas'),
				'Jarak' => $this->input->post('Jarak'),
				'Jumlah_cicil' => $this->input->post('Jumlah_cicil'),
				'Tahun_bangun' => $this->input->post('Tahun_bangun'),
            );
            
            $properti_id = $this->Properti_model->add_properti($params);
            redirect('properti/index');
        }
        else
        {            
            $data['_view'] = 'properti/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a properti
     */
    function edit($PropertiID)
    {   
        // check if the properti exists before trying to edit it
        $data['properti'] = $this->Properti_model->get_properti($PropertiID);
        
        if(isset($data['properti']['PropertiID']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('JenisID','JenisID','required|max_length[50]');
			$this->form_validation->set_rules('NamaProperti','NamaProperti','required|max_length[50]');
			$this->form_validation->set_rules('Alamat_properti','Alamat Properti','required|max_length[200]');
			$this->form_validation->set_rules('Longitude','Longitude','required|max_length[50]');
			$this->form_validation->set_rules('Latitude','Latitude','required|max_length[50]');
			$this->form_validation->set_rules('Harga','Harga','required|integer');
			$this->form_validation->set_rules('Jarak','Jarak','required');
			$this->form_validation->set_rules('Jumlah_cicil','Jumlah Cicil','required|integer');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'JenisID' => $this->input->post('JenisID'),
					'NamaProperti' => $this->input->post('NamaProperti'),
					'Alamat_properti' => $this->input->post('Alamat_properti'),
					'Longitude' => $this->input->post('Longitude'),
					'Latitude' => $this->input->post('Latitude'),
					'Harga' => $this->input->post('Harga'),
					'Luas' => $this->input->post('Luas'),
					'Jarak' => $this->input->post('Jarak'),
					'Jumlah_cicil' => $this->input->post('Jumlah_cicil'),
					'Tahun_bangun' => $this->input->post('Tahun_bangun'),
                );

                $this->Properti_model->update_properti($PropertiID,$params);            
                redirect('properti/index');
            }
            else
            {
                $data['_view'] = 'properti/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The properti you are trying to edit does not exist.');
    } 

    /*
     * Deleting properti
     */
    function remove($PropertiID)
    {
        $properti = $this->Properti_model->get_properti($PropertiID);

        // check if the properti exists before trying to delete it
        if(isset($properti['PropertiID']))
        {
            $this->Properti_model->delete_properti($PropertiID);
            redirect('properti/index');
        }
        else
            show_error('The properti you are trying to delete does not exist.');
    }
    
}
