<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Foto_tabel_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get foto_tabel by FotoID
     */
    function get_foto_tabel($FotoID)
    {
        return $this->db->get_where('foto_tabel',array('FotoID'=>$FotoID))->row_array();
    }
        
    /*
     * Get all foto_tabel
     */
    function get_all_foto_tabel()
    {
        $this->db->order_by('FotoID', 'desc');
        return $this->db->get('foto_tabel')->result_array();
    }
        
    /*
     * function to add new foto_tabel
     */
    function add_foto_tabel($params)
    {
        $this->db->insert('foto_tabel',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update foto_tabel
     */
    function update_foto_tabel($FotoID,$params)
    {
        $this->db->where('FotoID',$FotoID);
        return $this->db->update('foto_tabel',$params);
    }
    
    /*
     * function to delete foto_tabel
     */
    function delete_foto_tabel($FotoID)
    {
        return $this->db->delete('foto_tabel',array('FotoID'=>$FotoID));
    }
}
