<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Jenisproperti_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get jenisproperti by JenisID
     */
    function get_jenisproperti($JenisID)
    {
        return $this->db->get_where('jenisProperti',array('JenisID'=>$JenisID))->row_array();
    }
        
    /*
     * Get all jenisproperti
     */
    function get_all_jenisproperti()
    {
        $this->db->order_by('JenisID', 'desc');
        return $this->db->get('jenisProperti')->result_array();
    }
        
    /*
     * function to add new jenisproperti
     */
    function add_jenisproperti($params)
    {
        $this->db->insert('jenisProperti',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update jenisproperti
     */
    function update_jenisproperti($JenisID,$params)
    {
        $this->db->where('JenisID',$JenisID);
        return $this->db->update('jenisProperti',$params);
    }
    
    /*
     * function to delete jenisproperti
     */
    function delete_jenisproperti($JenisID)
    {
        return $this->db->delete('jenisProperti',array('JenisID'=>$JenisID));
    }
}
